apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: elasticsearchclusters.database.f110.dev
spec:
  group: database.f110.dev
  names:
    kind: ElasticsearchCluster
    listKind: ElasticsearchClusterList
    plural: elasticsearchclusters
    singular: elasticsearchcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
